name: Deploy Workflow
on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
      TURBO_TOKEN:
        required: true
        type: secret
      TURBO_TEAM:
        required: true
        type: secret
        
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Deploy
        env:
          TARGET: ${{ inputs.target }}
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
        run: echo "Deploying: $TARGET" && node --run deploy -- $TARGET
