name: CI

on:
  push:
    branches:
      - "**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use pnpm
        uses: pnpm/action-setup@v4

      - name: Use Nodejs
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: v3
        run: ls -la frontend/app/src
      - name: v4
        run: ls -la frontend/app/src/components

      - name: Turbo
        run: pnpm turbo lint build