name: ContinuosIntegration

on:
  pull_request:
    branches:
      - main

jobs:
  ci-checks:
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}

    steps:
      - name: Fetch Source Code
        uses: actions/checkout@v4
      - name: Use pnpm
        uses: pnpm/action-setup@v4
      - name: Use Nodejs
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Checks
        run: node --run checks

  ephemeral-deploy:
    needs: ci-checks
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}

    steps:
      - name: Fetch Source Code
        uses: actions/checkout@v4
      - name: Use pnpm
        uses: pnpm/action-setup@v4
      - name: Use Nodejs
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Deploy to Ephemeral Environment
        run: |
          export GITHUB_PR_USER=${{ github.event.pull_request.user.login }}
          USERNAME_MAPPING=$(node -e "const mappings = require('./.github/ephemeral-mappings.json'); console.log(mappings[process.env.GITHUB_PR_USER] || mappings.default);")
          echo "Using $USERNAME_MAPPING"
          node --run deploy "$USERNAME_MAPPING"

  staging-deploy:
    needs: [ci-checks, ephemeral-deploy]
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://staging.example.com
    
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}

    steps:
      - name: Fetch Source Code
        uses: actions/checkout@v4
      - name: Use pnpm
        uses: pnpm/action-setup@v4
      - name: Use Nodejs
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Deploy
        run: node --run deploy staging
