name: ContinuosIntegration

on:
  pull_request:
    branches:
      - main

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}

    steps:
      - name: Fetch Source Code
        uses: actions/checkout@v4
      - name: Use pnpm
        uses: pnpm/action-setup@v4
      - name: Use Nodejs
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'pnpm'
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Checks
        run: node --run checks